# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wrapper_v1.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wrapper_v1.proto',
  package='svrkit',
  syntax='proto3',
  serialized_pb=_b('\n\x10wrapper_v1.proto\x12\x06svrkit\"!\n\x0eRequestWrapper\x12\x0f\n\x07request\x18\x01 \x01(\x0c\",\n\x0fResponseWrapper\x12\x0b\n\x03RET\x18\x01 \x01(\x04\x12\x0c\n\x04\x44\x41TA\x18\x02 \x01(\x0c\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REQUESTWRAPPER = _descriptor.Descriptor(
  name='RequestWrapper',
  full_name='svrkit.RequestWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='svrkit.RequestWrapper.request', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=61,
)


_RESPONSEWRAPPER = _descriptor.Descriptor(
  name='ResponseWrapper',
  full_name='svrkit.ResponseWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='RET', full_name='svrkit.ResponseWrapper.RET', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DATA', full_name='svrkit.ResponseWrapper.DATA', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=107,
)

DESCRIPTOR.message_types_by_name['RequestWrapper'] = _REQUESTWRAPPER
DESCRIPTOR.message_types_by_name['ResponseWrapper'] = _RESPONSEWRAPPER

RequestWrapper = _reflection.GeneratedProtocolMessageType('RequestWrapper', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTWRAPPER,
  __module__ = 'wrapper_v1_pb2'
  # @@protoc_insertion_point(class_scope:svrkit.RequestWrapper)
  ))
_sym_db.RegisterMessage(RequestWrapper)

ResponseWrapper = _reflection.GeneratedProtocolMessageType('ResponseWrapper', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEWRAPPER,
  __module__ = 'wrapper_v1_pb2'
  # @@protoc_insertion_point(class_scope:svrkit.ResponseWrapper)
  ))
_sym_db.RegisterMessage(ResponseWrapper)


# @@protoc_insertion_point(module_scope)
